# Generated by Django 3.2.7 on 2021-12-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='Chú thích')),
                ('images', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
