# Generated by Django 3.2.7 on 2021-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='note',
            field=models.CharField(default='note photo', max_length=50, verbose_name='Chú thích'),
        ),
    ]
