# Generated by Django 3.2.7 on 2021-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_alter_photo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default='', max_length=10, verbose_name='Vị trí'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name_location',
            field=models.CharField(default='', max_length=10, verbose_name='Tên địa điểm'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='note',
            field=models.CharField(default='note photo', max_length=50, verbose_name='Chú thích ảnh'),
        ),
    ]
