# Generated by Django 4.0 on 2021-12-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20211226_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='name_location',
            field=models.CharField(default='', max_length=20, verbose_name='Tên địa điểm'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='note',
            field=models.CharField(default='note photo', max_length=50, verbose_name='Chú thích hình ảnh'),
        ),
    ]
