# Generated by Django 3.2.7 on 2021-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20211225_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email_footer',
            field=models.CharField(default='', max_length=100, verbose_name='Email '),
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Vị trí '),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Số điện thoại '),
        ),
    ]
